name: Generate Snake

on:
  schedule: # Run at 12 AM UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: jonathankerth
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generate Snake"
          git push
